# Generated by Django 5.2.1 on 2025-10-17 06:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_subTitle', models.CharField(max_length=100)),
                ('news_authorName', models.CharField(max_length=70)),
                ('news_authorImg', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='news/')),
                ('news_desc', tinymce.models.HTMLField()),
                ('news_image', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='news/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
