# Generated by Django 5.2.1 on 2025-10-22 03:38

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_authorImg',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_authorName',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('short_description', tinymce.models.HTMLField()),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profiles', to=settings.CABINET_FILE_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.author'),
        ),
    ]
