# Generated by Django 5.2.1 on 2025-10-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_news_authorimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='short_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
