# Generated by Django 5.2.1 on 2025-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_author_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_subTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
