# Generated by Django 5.2.1 on 2025-10-23 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_news_subtitle'),
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('header-right', 'Header Right'), ('under-menu', 'Under Menu'), ('under-banner', 'Under Banner')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_images', to=settings.CABINET_FILE_MODEL)),
            ],
        ),
    ]
