# Generated by Django 5.2.1 on 2025-10-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_advertisement_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('header-right', 'Header Right'), ('under-menu', 'Under Menu'), ('under-banner', 'Under Banner'), ('featured-top-left', 'Featured Top Left'), ('featured-bottom-left', 'Featured bottom Left'), ('under-featured', 'Under Featured'), ('mainNews-right', 'Right to Main News'), ('under-mainNews', 'Under MainNews'), ('under-rajniti', 'Under Rajniti'), ('under-health', 'Under Health'), ('under-artha', 'Under Artha'), ('under-international', 'Under International'), ('under-interview', 'Under Interview'), ('under-photo-feature', 'Under Photo Feature'), ('under-suchana-prabidhi', 'Under Suchana Prabidhi'), ('under-kala', 'Under Kala'), ('under-vivid-right', 'Right to vivid'), ('under-vivid', 'Under Vivid'), ('under-manoranjan', 'Under Manoranjan'), ('under-featured', 'Under Featured'), ('under-krishi', 'Under Krishi'), ('detail-top', 'Top on Detail'), ('detail-bottom1', 'Bottom1 on Detail'), ('detail-bottom2', 'Bottom2 on Detail')], max_length=70),
        ),
    ]
