# Generated by Django 5.2.1 on 2025-10-24 07:27

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_advertisement_position'),
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('header-right', 'Header Right'), ('under-menu', 'Under Menu'), ('under-banner', 'Under Banner'), ('featured-top-left', 'Featured Top Left'), ('featured-bottom-left', 'Featured bottom Left'), ('under-featured', 'Under Featured'), ('mainNews-right', 'Right to Main News'), ('under-mainNews', 'Under MainNews'), ('under-rajniti', 'Under Rajniti'), ('under-health', 'Under Health'), ('under-artha', 'Under Artha'), ('under-international', 'Under International'), ('under-interview', 'Under Interview'), ('under-photo-feature', 'Under Photo Feature'), ('under-suchana-prabidhi', 'Under Suchana Prabidhi'), ('under-kala', 'Under Kala'), ('under-vivid-right', 'Right to vivid'), ('under-vivid', 'Under Vivid'), ('under-manoranjan', 'Under Manoranjan'), ('detail-top', 'Top on Detail'), ('detail-bottom1', 'Bottom1 on Detail'), ('detail-bottom2', 'Bottom2 on Detail')], max_length=70),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('हाम्रो टिम', 'हाम्रो टिम'), ('हाम्रो बारेमा', 'हाम्रो बारेमा'), ('गोपनीय नीति', 'गोपनीय नीति'), ('सम्पर्क गर्नुहोस्', 'सम्पर्क गर्नुहोस्')], max_length=50, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_images', to=settings.CABINET_FILE_MODEL)),
            ],
        ),
    ]
