# Generated by Django 5.2.1 on 2025-10-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_advertisement_position_page'),
        migrations.swappable_dependency(settings.CABINET_FILE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_images', to=settings.CABINET_FILE_MODEL)),
            ],
        ),
    ]
